### ISSUE TITLE
Getting Allowed memory

### ISSUE THREAD

**Issue by kossa** [dcblogdev/laravel-db-sync#18]
Hello,

I have a big DB, when I try the sync I get error something like: `Allowed memory size of 536870912 bytes exhausted (tried to allocate 477174084 bytes)`

**Comment by m-popa** [comment]
Hello and thank you for the package. Same issue on 13mb gziped database. Any solution?

**Comment by nawazsarwar** [comment]
Hi there
I think If you are having this memory size warning, you have two choices
1. You may increase the Memory Limit in you php ini file.
2. You may also choose to increasing the memory at the start of handle function in the command of this package with somthing like ini_set('memory_limit', '256M');, though changes will be lost if you upgrade the package in future.

Note: The memory limit as an option may be added in the config file of the package
