### ISSUE TITLE
Connecting via SSH

### ISSUE THREAD

**Issue by victor-falcon** [dcblogdev/laravel-db-sync#3]
First, congrats, I think that this package it's super useful! 🎉 

While trying to make it work with my production database, I notice that I need to open and SSH server to connect to my production database because it's protected.

With something similar to this, it could be possible:

```php

// Open a tunnel from remote host with remote user and bind it in localhost:3307
shell_exec("ssh -f -L 3307:127.0.0.1:3306 $remoteUser@$remoteHost sleep 60 >> logfile");

// Then connect to localhost 3307
exec("mysqldump -h 127.0.0.1 -P 3307 -u $username -p$password $database --column-statistics=0 $ignoreString > file.sql",
                $output);
```

What do you think?

**Comment by dcblogdev** [comment]
Thanks, I'm already using this on multiple projects.

Yeah, it would be good to be able to use it over ssh as well.

**Comment by dcblogdev** [comment]
okay I've got this working with both SSH and without SSH.

Going to do some cleanup and testing and should have this released later today.

**Comment by dcblogdev** [comment]
I've added options to connect over SSH now 

```
REMOTE_USE_SSH=true
REMOTE_SSH_PORT=22
REMOTE_SSH_USERNAME=
REMOTE_DATABASE_HOST=

REMOTE_DATABASE_USERNAME=
REMOTE_DATABASE_NAME=
REMOTE_DATABASE_PASSWORD=
REMOTE_DATABASE_IGNORE_TABLES=''

REMOTE_REMOVE_FILE_AFTER_IMPORT=true
REMOTE_IMPORT_FILE=true
```

I've released this now.

You will need to re-publish the config file and add the above .env variables.
