### ISSUE TITLE
Database password containing special char

### ISSUE THREAD

**Issue by abduromanov** [dcblogdev/laravel-db-sync#8]
Cannot connect remote database if the password containing the character like brackets

**Comment by NanoNulla** [comment]
I had the same issue in ubuntu and Laravel. The password was generated by password generator sites and it included the hash (#), Laravel .env file ignores the strings after "#" so the solution is the surround the password with quotations. 

Let me check the issue if I was able to solve it.

**Comment by zieru** [comment]
> I had the same issue in ubuntu and Laravel. The password was generated by password generator sites and it included the hash (#), Laravel .env file ignores the strings after "#" so the solution is the surround the password with quotations.
> 
> Let me check the issue if I was able to solve it.

i think your problem is not only Laravel env , even if env escapes with surronding quotes, it will still have problem in mysqldump
